# 第5章 pandas入门

In [1]:
import pandas as pd

In [3]:
from pandas import Series, DataFrame

## 5.1 pandas的数据结构介绍

### Series

In [4]:
obj=pd.Series([4,7,-5,3])

In [5]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [6]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2=pd.Series([ 4,  7, -5,  3],index=['d','b','a','c'])

In [9]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [10]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [11]:
obj2['d']

4

In [12]:
a=['a','b','c']

In [13]:
obj2[a]

a   -5
b    7
c    3
dtype: int64

In [16]:
obj2[['a']]

a   -5
dtype: int64

In [17]:
obj2>0

d     True
b     True
a    False
c     True
dtype: bool

In [18]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [19]:
obj2*2

d     8
b    14
a   -10
c     6
dtype: int64

In [20]:
np.exp(obj2)

NameError: name 'np' is not defined

In [22]:
import numpy as np

In [23]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [24]:
'b' in obj2

True

In [25]:
sdata={'O':35000,'T':71000,'Or':16000,'U':5000}

In [27]:
obj3=pd.Series(sdata)

In [28]:
obj3

O     35000
T     71000
Or    16000
U      5000
dtype: int64

In [29]:
states=['C','O','Or','T']

In [30]:
obj4=pd.Series(sdata,index=states)

In [31]:
obj4

C         NaN
O     35000.0
Or    16000.0
T     71000.0
dtype: float64

In [32]:
pd.isnull(obj4)

C      True
O     False
Or    False
T     False
dtype: bool

In [33]:
pd.notnull(obj4)

C     False
O      True
Or     True
T      True
dtype: bool

In [34]:
obj4.isnull()

C      True
O     False
Or    False
T     False
dtype: bool

In [35]:
obj3+obj4

C          NaN
O      70000.0
Or     32000.0
T     142000.0
U          NaN
dtype: float64

In [40]:
obj4.name='population'

In [41]:
obj4

C         NaN
O     35000.0
Or    16000.0
T     71000.0
Name: population, dtype: float64

In [43]:
obj4.index.name='state'

In [45]:
obj4.index

Index(['C', 'O', 'Or', 'T'], dtype='object', name='state')

In [46]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [47]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [48]:
obj.index=['B','S','J','R']

In [49]:
obj

B    4
S    7
J   -5
R    3
dtype: int64

### DataFrame

In [50]:
data={'state':['O','O','O','N','N','N'],
     'year':[2000,2001,2002,2001,2002,2003],
     'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}

In [51]:
data

{'state': ['O', 'O', 'O', 'N', 'N', 'N'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [52]:
frame=pd.DataFrame(data)

In [53]:
frame

state  year  pop
0     O  2000  1.5
1     O  2001  1.7
2     O  2002  3.6
3     N  2001  2.4
4     N  2002  2.9
5     N  2003  3.2

In [56]:
gods={'姓名':['锅','锅家属','蛋总'],
    '特点':['外白内黑','不吃姜，不吃羊肉','很不想继承家族企业']}

In [57]:
gods

{'姓名': ['锅', '锅家属', '蛋总'], '特点': ['外白内黑', '不吃姜，不吃羊肉', '很不想继承家族企业']}

In [58]:
god_data=pd.DataFrame(gods)

In [59]:
god_data

姓名         特点
0    锅       外白内黑
1  锅家属   不吃姜，不吃羊肉
2   蛋总  很不想继承家族企业

In [60]:
frame2=pd.DataFrame(data,columns=['year','state','pop','debt']
                    ,index=['one','two','three','four','five','six'])

In [61]:
frame2

year state  pop debt
one    2000     O  1.5  NaN
two    2001     O  1.7  NaN
three  2002     O  3.6  NaN
four   2001     N  2.4  NaN
five   2002     N  2.9  NaN
six    2003     N  3.2  NaN

In [62]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [63]:
frame2['state']

one      O
two      O
three    O
four     N
five     N
six      N
Name: state, dtype: object

In [64]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [65]:
frame2.year.name

'year'

In [66]:
frame2['state'].name

'state'

In [67]:
frame2.loc['three']

year     2002
state       O
pop       3.6
debt      NaN
Name: three, dtype: object

In [68]:
frame2.debt=16.5

In [69]:
frame2

year state  pop  debt
one    2000     O  1.5  16.5
two    2001     O  1.7  16.5
three  2002     O  3.6  16.5
four   2001     N  2.4  16.5
five   2002     N  2.9  16.5
six    2003     N  3.2  16.5

In [72]:
frame2.debt.loc['two']=2

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:190: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [75]:
frame2['debt'].loc['three']=3.0

In [76]:
frame2

year state  pop  debt
one    2000     O  1.5  16.5
two    2001     O  1.7   2.0
three  2002     O  3.6   3.0
four   2001     N  2.4  16.5
five   2002     N  2.9  16.5
six    2003     N  3.2  16.5

In [80]:
frame2.loc['five']['debt']=5.0

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [89]:
frame2.debt=np.arange(6.)

In [85]:
frame2

year state  pop  debt
one    2000     O  1.5   0.0
two    2001     O  1.7   1.0
three  2002     O  3.6   2.0
four   2001     N  2.4   3.0
five   2002     N  2.9   4.0
six    2003     N  3.2   5.0

In [91]:
val=pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])

In [92]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [93]:
val.index

Index(['two', 'four', 'five'], dtype='object')

In [97]:
val.values

array([-1.2, -1.5, -1.7])

In [98]:
frame2.debt=val

In [99]:
frame2

year state  pop  debt
one    2000     O  1.5   NaN
two    2001     O  1.7  -1.2
three  2002     O  3.6   NaN
four   2001     N  2.4  -1.5
five   2002     N  2.9  -1.7
six    2003     N  3.2   NaN

In [100]:
frame2.eastern=frame2.state=='O'

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  """Entry point for launching an IPython kernel.


In [101]:
frame2

year state  pop  debt
one    2000     O  1.5   NaN
two    2001     O  1.7  -1.2
three  2002     O  3.6   NaN
four   2001     N  2.4  -1.5
five   2002     N  2.9  -1.7
six    2003     N  3.2   NaN

In [111]:
frame2['eastern']=frame2.state=='O'

In [112]:
frame2

year state  pop  debt  eastern
one    2000     O  1.5   NaN     True
two    2001     O  1.7  -1.2     True
three  2002     O  3.6   NaN     True
four   2001     N  2.4  -1.5    False
five   2002     N  2.9  -1.7    False
six    2003     N  3.2   NaN    False

In [113]:
del frame2.eastern

AttributeError: eastern

In [114]:
del frame2['eastern']

In [115]:
frame2

year state  pop  debt
one    2000     O  1.5   NaN
two    2001     O  1.7  -1.2
three  2002     O  3.6   NaN
four   2001     N  2.4  -1.5
five   2002     N  2.9  -1.7
six    2003     N  3.2   NaN

In [116]:
pop={'N':{2001:2.4,2002:2.9},
    'O':{2000:1.5,2001:1.7,2002:3.6}}

In [117]:
pop

{'N': {2001: 2.4, 2002: 2.9}, 'O': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [118]:
frame3=pd.DataFrame(pop)

In [119]:
frame3

N    O
2000  NaN  1.5
2001  2.4  1.7
2002  2.9  3.6

In [120]:
frame3.T

2000  2001  2002
N   NaN   2.4   2.9
O   1.5   1.7   3.6

In [121]:
frame3

N    O
2000  NaN  1.5
2001  2.4  1.7
2002  2.9  3.6

In [122]:
pd.DataFrame(pop,index=[2001,2002,2003])

N    O
2001  2.4  1.7
2002  2.9  3.6
2003  NaN  NaN

In [123]:
frame3.O[:]

2000    1.5
2001    1.7
2002    3.6
Name: O, dtype: float64

In [128]:
frame3[frame3.O==1.7]

N    O
2001  2.4  1.7

In [129]:
frame3.O==1.7

2000    False
2001     True
2002    False
Name: O, dtype: bool

In [130]:
frame3.index

Int64Index([2000, 2001, 2002], dtype='int64')

In [131]:
frame3.columns

Index(['N', 'O'], dtype='object')

In [132]:
frame.values

array([['O', 2000, 1.5, nan],
       ['O', 2001, 1.7, nan],
       ['O', 2002, 3.6, nan],
       ['N', 2001, 2.4, nan],
       ['N', 2002, 2.9, nan],
       ['N', 2003, 3.2, nan]], dtype=object)

### 索引对象

In [133]:
obj=pd.Series(range(3),index=['a','b','c'])

In [134]:
obj

a    0
b    1
c    2
dtype: int64

In [135]:
obj.index

Index(['a', 'b', 'c'], dtype='object')

In [139]:
obj.values

array([0, 1, 2], dtype=int64)

In [140]:
obj.index.unique

<bound method Index.unique of Index(['a', 'b', 'c'], dtype='object')>

## 5.2 基本功能

### 重新索引

In [141]:
obj=pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])

In [142]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [145]:
obj2=obj.reindex(['b','a','c','d','e'])

In [146]:
obj2

b    7.2
a   -5.3
c    3.6
d    4.5
e    NaN
dtype: float64

In [147]:
obj3=pd.Series(['blue','purple','yellow'],index=[0,2,4])

In [148]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [149]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [150]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [151]:
frame=pd.DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],columns=['O','T','C'])

In [152]:
frame

O  T  C
a  0  1  2
c  3  4  5
d  6  7  8

In [153]:
frame2=frame.reindex(['a','b','c','d'])

In [154]:
frame

O  T  C
a  0  1  2
c  3  4  5
d  6  7  8

In [155]:
frame2

O    T    C
a  0.0  1.0  2.0
b  NaN  NaN  NaN
c  3.0  4.0  5.0
d  6.0  7.0  8.0

In [158]:
s1=range(5)

In [159]:
s1

range(0, 5)

In [161]:
s2=np.arange(5)

In [162]:
s2

array([0, 1, 2, 3, 4])

In [176]:
s3=range(1,5,2)

In [177]:
s3

range(1, 5, 2)

In [178]:
list(s3)

[1, 3]

### 丢弃指定轴上的项

In [180]:
obj=pd.Series(np.arange(5.), index=['a','b','c','d','e'])

In [181]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [182]:
new_obj=obj.drop('c')

In [183]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [184]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [185]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),
                 index=['O','C','U','N'],columns=['one','two','three','four'])

In [186]:
data

one  two  three  four
O    0    1      2     3
C    4    5      6     7
U    8    9     10    11
N   12   13     14    15

In [187]:
data.drop(['C','O'])

one  two  three  four
U    8    9     10    11
N   12   13     14    15

In [188]:
data

one  two  three  four
O    0    1      2     3
C    4    5      6     7
U    8    9     10    11
N   12   13     14    15

In [189]:
data.drop(['two','three'],1)

one  four
O    0     3
C    4     7
U    8    11
N   12    15

In [191]:
#inplace原地替换

### 索引、选取和过滤

In [198]:
obj=pd.Series(np.arange(5,9.),index=['a','b','c','d'])

In [199]:
obj

a    5.0
b    6.0
c    7.0
d    8.0
dtype: float64

In [200]:
obj[2:4]

c    7.0
d    8.0
dtype: float64

In [201]:
# 利用标签的切片 包含末端
obj['b':]

b    6.0
c    7.0
d    8.0
dtype: float64

In [202]:
data

one  two  three  four
O    0    1      2     3
C    4    5      6     7
U    8    9     10    11
N   12   13     14    15

In [203]:
data.two

O     1
C     5
U     9
N    13
Name: two, dtype: int32

In [205]:
data[['three','four']]

three  four
O      2     3
C      6     7
U     10    11
N     14    15

In [206]:
data[:2]

one  two  three  four
O    0    1      2     3
C    4    5      6     7

In [221]:
data.columns

Index(['one', 'two', 'three', 'four'], dtype='object')

In [222]:
data.index

Index(['O', 'C', 'U', 'N'], dtype='object')

In [223]:
# data[:2]选行，向[]传递单一的元素或列表，就可以选列

In [224]:
data[data<5]

one  two  three  four
O  0.0  1.0    2.0   3.0
C  4.0  NaN    NaN   NaN
U  NaN  NaN    NaN   NaN
N  NaN  NaN    NaN   NaN

### 用loc和iloc进行选取

In [225]:
data.loc['C',['two','three']]

two      5
three    6
Name: C, dtype: int32

In [226]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: U, dtype: int32

In [227]:
data.iloc[:,[3,0,1]]

four  one  two
O     3    0    1
C     7    4    5
U    11    8    9
N    15   12   13

In [228]:
data.iloc[2,[:]]

SyntaxError: invalid syntax (<ipython-input-228-40b5c4f09fc5>, line 1)

In [230]:
data.iloc[:,np.arange(2)]

one  two
O    0    1
C    4    5
U    8    9
N   12   13

In [231]:
data.iloc[:,0:2]

one  two
O    0    1
C    4    5
U    8    9
N   12   13

In [235]:
data.iloc[:2]

one  two  three  four
O    0    1      2     3
C    4    5      6     7

In [236]:
data.loc[:'U','two':'four']

two  three  four
O    1      2     3
C    5      6     7
U    9     10    11

In [237]:
data.iloc[:,:3][data.three>5]

one  two  three
C    4    5      6
U    8    9     10
N   12   13     14

### 整数索引

###### 如果轴索引含有整数，数据选取总会使用标签。为了准确，请使用loc或iloc

### 算术运算和数据对齐

In [238]:
# 在将对象相加时，如果存在不同的索引对，则结果的索引就是该索引对的并集。
# 就像在索引标签上进行自动外连接。

In [239]:
s1=pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])

In [240]:
s2=pd.Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])

In [241]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [242]:
sum(a,b)

NameError: name 'b' is not defined

In [243]:
# 对于DataFrame,对齐操作会同时发生在行列索引标签上

### 在算术方法中填充值

In [244]:
df1=pd.DataFrame(np.arange(12.).reshape((3,4)),
                    columns=list('abcd'))

In [245]:
df2=pd.DataFrame(np.arange(20.).reshape((4,5)),
                    columns=list('abcde'))

In [246]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [247]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [248]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [249]:
df1.add(df2,fill_value=-99999999)

a           b           c           d           e
0         0.0         2.0         4.0         6.0 -99999995.0
1         9.0        11.0        13.0        15.0 -99999990.0
2        18.0        20.0        22.0        24.0 -99999985.0
3 -99999984.0 -99999983.0 -99999982.0 -99999981.0 -99999980.0

### DataFrame和Series之间的运算

In [250]:
arr=np.arange(12.).reshape((3,4))

In [251]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [252]:
arr[0]

array([0., 1., 2., 3.])

In [253]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [254]:
frame

O  T  C
a  0  1  2
c  3  4  5
d  6  7  8

In [255]:
frame1

NameError: name 'frame1' is not defined

In [256]:
frame2

O    T    C
a  0.0  1.0  2.0
b  NaN  NaN  NaN
c  3.0  4.0  5.0
d  6.0  7.0  8.0

In [257]:
frame3

N    O
2000  NaN  1.5
2001  2.4  1.7
2002  2.9  3.6

In [258]:
frame4

NameError: name 'frame4' is not defined

In [259]:
frame=pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),
                    index=['U','O','T','Or'])

In [293]:
series=frame.iloc[0]

In [261]:
frame

b     d     e
U   0.0   1.0   2.0
O   3.0   4.0   5.0
T   6.0   7.0   8.0
Or  9.0  10.0  11.0

In [262]:
series

b    0.0
d    1.0
e    2.0
Name: U, dtype: float64

In [263]:
frame-series

b    d    e
U   0.0  0.0  0.0
O   3.0  3.0  3.0
T   6.0  6.0  6.0
Or  9.0  9.0  9.0

In [264]:
series2=pd.Series(range(3),
                    index=['b','e','f'])

In [265]:
frame+series2

b   d     e   f
U   0.0 NaN   3.0 NaN
O   3.0 NaN   6.0 NaN
T   6.0 NaN   9.0 NaN
Or  9.0 NaN  12.0 NaN

In [266]:
series3=frame['d']

In [267]:
series3

U      1.0
O      4.0
T      7.0
Or    10.0
Name: d, dtype: float64

In [268]:
frame

b     d     e
U   0.0   1.0   2.0
O   3.0   4.0   5.0
T   6.0   7.0   8.0
Or  9.0  10.0  11.0

In [269]:
frame.sub(series3,axis=0)

b    d    e
U  -1.0  0.0  1.0
O  -1.0  0.0  1.0
T  -1.0  0.0  1.0
Or -1.0  0.0  1.0

In [270]:
frame

b     d     e
U   0.0   1.0   2.0
O   3.0   4.0   5.0
T   6.0   7.0   8.0
Or  9.0  10.0  11.0

In [271]:
frame.sub(series3,axis=1)

O  Or   T   U   b   d   e
U  NaN NaN NaN NaN NaN NaN NaN
O  NaN NaN NaN NaN NaN NaN NaN
T  NaN NaN NaN NaN NaN NaN NaN
Or NaN NaN NaN NaN NaN NaN NaN

### 函数应用和映射

In [272]:
frame

b     d     e
U   0.0   1.0   2.0
O   3.0   4.0   5.0
T   6.0   7.0   8.0
Or  9.0  10.0  11.0

In [273]:
frame=pd.DataFrame(np.random.randn(4,3),columns=list('bde'),
                  index=['U','O','T','Or'])

In [274]:
frame

b         d         e
U  -0.635733  0.199129  1.448868
O  -0.802222  0.075684 -0.095436
T   0.795284 -0.874133  0.848726
Or  0.555446 -0.115862 -2.548029

In [275]:
np.abs(frame)

b         d         e
U   0.635733  0.199129  1.448868
O   0.802222  0.075684  0.095436
T   0.795284  0.874133  0.848726
Or  0.555446  0.115862  2.548029

In [276]:
f=lambda x: x.max()-x.min()

In [277]:
frame.apply(f)

b    1.597505
d    1.073262
e    3.996897
dtype: float64

In [278]:
frame.apply(f,0)

b    1.597505
d    1.073262
e    3.996897
dtype: float64

In [279]:
def f(x):
    return pd.Series([x.min(),x.max()]
                    , index=['min','max'])

In [280]:
frame.apply(f)

b         d         e
min -0.802222 -0.874133 -2.548029
max  0.795284  0.199129  1.448868

In [281]:
frame.apply(f,1)

min       max
U  -0.635733  1.448868
O  -0.802222  0.075684
T  -0.874133  0.848726
Or -2.548029  0.555446

In [282]:
format=lambda x: '%.2f' % x

In [283]:
frame.applymap(format)

b      d      e
U   -0.64   0.20   1.45
O   -0.80   0.08  -0.10
T    0.80  -0.87   0.85
Or   0.56  -0.12  -2.55

In [284]:
frame['e']

U     1.448868
O    -0.095436
T     0.848726
Or   -2.548029
Name: e, dtype: float64

In [285]:
frame['e'].map(format)

U      1.45
O     -0.10
T      0.85
Or    -2.55
Name: e, dtype: object

### 排序和排名

In [286]:
obj=pd.Series(range(4)
             , index=list('dabc'))

In [287]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [288]:
frame=pd.DataFrame(np.arange(8).reshape((2,4))
                  , index=['three','one']
                  , columns=list('dabc'))

In [289]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [295]:
frame.sort_index(1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [303]:
frame.sort_index(1,ascending=)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [304]:
obj=pd.Series([4,7,-3,2])

In [305]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [306]:
obj=pd.Series([4,np.nan,7,np.nan,-3,2])

In [307]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [318]:
frame=pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

In [319]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [320]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [322]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [323]:
obj=pd.Series([7,5,7,4,2,0,4])

In [324]:
obj.rank()

0    6.5
1    5.0
2    6.5
3    3.5
4    2.0
5    1.0
6    3.5
dtype: float64

In [325]:
obj.rank(method='first')

0    6.0
1    5.0
2    7.0
3    3.0
4    2.0
5    1.0
6    4.0
dtype: float64

### 带有重复标签的轴索引

In [326]:
obj=pd.Series(range(5),index=list('aabbc'))

In [327]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [328]:
obj.index.is_unique

False

In [329]:
obj['a']

a    0
a    1
dtype: int64

In [330]:
# 这样很不好

## 5.3 汇总和计算描述统计

In [331]:
df=pd.DataFrame([[1.4,np.nan]
                ,[7.1,-4.5]
                ,[np.nan,np.nan]
                ,[0.75,-1.3]]
               , index=list('abcd')
               , columns=['one','two'])

In [332]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [333]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [334]:
df.sum(1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [335]:
df.sum(1,skipna=0)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [336]:
df.idxmax()

one    b
two    d
dtype: object

In [337]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [338]:
df.cumsum(1)

one   two
a  1.40   NaN
b  7.10  2.60
c   NaN   NaN
d  0.75 -0.55

In [339]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [340]:
df.cumsum(0)

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [341]:
df.sum(0)

one    9.25
two   -5.80
dtype: float64

In [342]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [343]:
obj=pd.Series(list('aabc')*4)

In [344]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [345]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### 相关系数和协方差

In [353]:
import pandas_datareader.data as web

In [354]:
all_data={ticker:web.get_data_yahoo(ticker) for ticker in ['AAPL','IBM','MSFT','GOOG']}

In [356]:
price=pd.DataFrame({ticker:data['Adj Close'] for ticker, data in all_data.items()})

In [358]:
volume=pd.DataFrame({ticker:data['Volume'] for ticker, data in all_data.items()})

In [359]:
returns=price.pct_change()

In [360]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2019-05-09 -0.010744 -0.007626 -0.000080 -0.003335
2019-05-10 -0.013853 -0.000148  0.012988  0.001626
2019-05-13 -0.058119 -0.028821 -0.029733 -0.027691
2019-05-14  0.015830  0.014381  0.011188 -0.010238
2019-05-15  0.007710  0.007426  0.010382  0.032844

In [361]:
returns['MSFT'].corr(returns['IBM'])

0.4869769647795616

In [362]:
returns['MSFT'].cov(returns['IBM'])

8.678938781108908e-05

In [363]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.373161  0.449999  0.456579
IBM   0.373161  1.000000  0.486977  0.404140
MSFT  0.449999  0.486977  1.000000  0.534827
GOOG  0.456579  0.404140  0.534827  1.000000

In [364]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000271  0.000076  0.000107  0.000116
IBM   0.000076  0.000152  0.000087  0.000077
MSFT  0.000107  0.000087  0.000209  0.000120
GOOG  0.000116  0.000077  0.000120  0.000239

In [365]:
returns.corrwith(returns.IBM)

AAPL    0.373161
IBM     1.000000
MSFT    0.486977
GOOG    0.404140
dtype: float64

In [366]:
volume

AAPL         IBM         MSFT        GOOG
Date                                                        
2009-12-31   88102700.0   4223400.0   31929700.0   2455400.0
2010-01-04  123432400.0   6155300.0   38409100.0   3937800.0
2010-01-05  150476200.0   6841400.0   49749600.0   6048500.0
2010-01-06  138040000.0   5605300.0   58182400.0   8009000.0
2010-01-07  119282800.0   5840600.0   50559700.0  12912000.0
2010-01-08  111902700.0   4197200.0   51197400.0   9509900.0
2010-01-11  115557400.0   5730400.0   68754700.0  14519600.0
2010-01-12  148614900.0   8081500.0   65912100.0   9769600.0
2010-01-13  151473000.0   6455400.0   51863500.0  13077600.0
2010-01-14  108223500.0   7111800.0   63228100.0   8535300.0
2010-01-15  148516900.0   8494400.0   79913200.0  10939600.0
2010-01-19  182501900.0  13916200.0   46575700.0   8689500.0
2010-01-20  153038200.0  15197500.0   54849500.0   6543600.0
2010-01-21  152038600.0   9608600.0   73086700.0  12697400.0
2010-01-22  220441900.0  10088600.0  102004600.0  13689200.0
2010-01-25  266424900.0   5738500.0   63373000.0   8897200.0
2010-01-26  466777500.0   7135300.0   66639900.0   8767600.0
2010-01-27  430642100.0   8719200.0   63949500.0   7980200.0
2010-01-28  293375600.0   9622200.0  117513700.0   6500100.0
2010-01-29  311488100.0  11571200.0  193888500.0   8334700.0
2010-02-01  187469100.0   7242900.0   85931100.0   4530800.0
2010-02-02  174585600.0   5899900.0   54413700.0   8245600.0
2010-02-03  153832000.0   4177100.0   61397900.0   6037000.0
2010-02-04  189413000.0   9126900.0   77850000.0   6799200.0
2010-02-05  212576700.0   8617000.0   80960100.0   6353000.0
2010-02-08  119567700.0   5718500.0   52820600.0   5423500.0
2010-02-09  158221700.0   6044500.0   59195800.0   5675700.0
2010-02-10   92590400.0   5219100.0   48591300.0   5383700.0
2010-02-11  137586400.0   5089000.0   65993700.0   4851300.0
2010-02-12  163867200.0   8017700.0   81117200.0   4589000.0
...                 ...         ...          ...         ...
2019-04-03   23271800.0   2681200.0   22860700.0   1017800.0
2019-04-04   19114300.0   2771100.0   20112800.0    950000.0
2019-04-05   18526600.0   2731800.0   15826200.0    907200.0
2019-04-08   25881700.0   2118200.0   15116200.0    860200.0
2019-04-09   35768200.0   3038500.0   17612000.0    876400.0
2019-04-10   21695300.0   2678000.0   16477200.0    724600.0
2019-04-11   20900800.0   2942000.0   14209100.0    710200.0
2019-04-12   27760700.0   2898900.0   19745100.0    933400.0
2019-04-15   17536600.0   3603200.0   15792600.0   1187400.0
2019-04-16   25696400.0   6301700.0   14071800.0    856300.0
2019-04-17   28906800.0  12525700.0   19300900.0   1221900.0
2019-04-18   24195800.0   4960000.0   27991000.0   1331800.0
2019-04-22   19439500.0   4494000.0   15648700.0    807300.0
2019-04-23   23323000.0   4462200.0   24025500.0   1319900.0
2019-04-24   17540600.0   2774900.0   31257000.0   1018800.0
2019-04-25   18543200.0   2910100.0   38033900.0   1107300.0
2019-04-26   18649100.0   2319800.0   23654900.0   1241400.0
2019-04-29   22204700.0   2958300.0   16324200.0   2499400.0
2019-04-30   46534900.0   4638800.0   24166500.0   6207000.0
2019-05-01   64827300.0   3053700.0   26821700.0   2639200.0
2019-05-02   31996300.0   3541400.0   27350200.0   1944800.0
2019-05-03   20892400.0   2579900.0   24911100.0   1980700.0
2019-05-06   32443100.0   2793300.0   24239800.0   1563900.0
2019-05-07   38763700.0   4726800.0   36017700.0   1551400.0
2019-05-08   26339500.0   3818900.0   28419000.0   1309300.0
2019-05-09   34908600.0   4192700.0   27235800.0   1185700.0
2019-05-10   41208700.0   3977600.0   30915100.0   1314500.0
2019-05-13   57430600.0   4958000.0   33944900.0   1860600.0
2019-05-14   35629000.0   3252200.0   25253400.0   1820200.0
2019-05-15   11485363.0    821332.0    9558670.0    887208.0

[2358 rows x 4 columns]

In [367]:
returns

AAPL       IBM      MSFT      GOOG
Date                                              
2009-12-31       NaN       NaN       NaN       NaN
2010-01-04  0.015565  0.011841  0.015420  0.010920
2010-01-05  0.001729 -0.012080  0.000323 -0.004404
2010-01-06 -0.015906 -0.006496 -0.006137 -0.025209
2010-01-07 -0.001849 -0.003462 -0.010400 -0.023279
2010-01-08  0.006648  0.010035  0.006897  0.013331
2010-01-11 -0.008822 -0.010470 -0.012720 -0.001512
2010-01-12 -0.011375  0.007955 -0.006607 -0.017684
2010-01-13  0.014106 -0.002145  0.009312 -0.005741
2010-01-14 -0.005792  0.015972  0.020099  0.004701
2010-01-15 -0.016712 -0.004006 -0.003230 -0.016699
2010-01-19  0.044238  0.017908  0.007777  0.013138
2010-01-20 -0.015392 -0.028999 -0.016399 -0.012270
2010-01-21 -0.017286 -0.009597 -0.018960  0.004428
2010-01-22 -0.049599 -0.027132 -0.034988 -0.056554
2010-01-25  0.026903  0.004940  0.012431 -0.018200
2010-01-26  0.014133 -0.002934  0.006139  0.004481
2010-01-27  0.009420  0.004612  0.005763 -0.000590
2010-01-28 -0.041322 -0.020423 -0.017190 -0.014407
2010-01-29 -0.036279 -0.010990 -0.033608 -0.008142
2010-02-01  0.013902  0.018629  0.008162  0.005812
2010-02-02  0.005803  0.006898  0.001760 -0.003565
2010-02-03  0.017206  0.001036  0.005973  0.018263
2010-02-04 -0.036038 -0.021168 -0.027593 -0.025961
2010-02-05  0.017756  0.004227  0.006466  0.008562
2010-02-08 -0.006856 -0.008864 -0.010707  0.004103
2010-02-09  0.010664  0.010912  0.010462  0.005567
2010-02-10 -0.005454 -0.003246 -0.000714 -0.003710
2010-02-11  0.018194  0.007492  0.004645  0.003649
2010-02-12  0.008607  0.002182 -0.006757 -0.006115
...              ...       ...       ...       ...
2019-04-03  0.006855  0.004406  0.006544  0.004523
2019-04-04  0.001740 -0.005918 -0.005085  0.007529
2019-04-05  0.006694  0.003502  0.004440 -0.006461
2019-04-08  0.015736  0.000768  0.000334 -0.002742
2019-04-09 -0.002999 -0.008927 -0.005420 -0.005474
2019-04-10  0.005614  0.006404  0.007629  0.004101
2019-04-11 -0.008324  0.005314  0.001165  0.002046
2019-04-12 -0.000402  0.003964  0.005152  0.010999
2019-04-15  0.001810 -0.003117  0.000827  0.002652
2019-04-16  0.000100  0.008617 -0.002313  0.004938
2019-04-17  0.019473 -0.041546  0.008280  0.007505
2019-04-18  0.003594  0.008770  0.013140  0.000024
2019-04-22  0.003287 -0.010262  0.003161  0.010086
2019-04-23  0.014423  0.011160  0.013575  0.012580
2019-04-24 -0.001542 -0.003489 -0.003428 -0.006761
2019-04-25 -0.009075 -0.009432  0.033117  0.005931
2019-04-26 -0.004774  0.005843  0.005730  0.006910
2019-04-29  0.001517 -0.002797 -0.000924  0.012105
2019-04-30 -0.019256  0.008774  0.006396 -0.076966
2019-05-01  0.049086  0.002067 -0.020827 -0.017165
2019-05-02 -0.006508 -0.006901 -0.013059 -0.004683
2019-05-03  0.012431  0.004728  0.021314  0.019602
2019-05-06 -0.015443  0.000927 -0.005818  0.003366
2019-05-07 -0.026957 -0.019518 -0.020523 -0.012855
2019-05-08  0.000197  0.002616 -0.000080 -0.006669
2019-05-09 -0.010744 -0.007626 -0.000080 -0.003335
2019-05-10 -0.013853 -0.000148  0.012988  0.001626
2019-05-13 -0.058119 -0.028821 -0.029733 -0.027691
2019-05-14  0.015830  0.014381  0.011188 -0.010238
2019-05-15  0.007710  0.007426  0.010382  0.032844

[2358 rows x 4 columns]

### 唯一值、值计数以及成员资格

In [368]:
obj=pd.Series(list('cadaabbcc'))

In [369]:
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

In [370]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [373]:
obj.values.pd.value_counts(sort=False)

AttributeError: 'numpy.ndarray' object has no attribute 'pd'

In [375]:
pd.value_counts(obj.values)

a    3
c    3
b    2
d    1
dtype: int64

In [376]:
obj.values

array(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'], dtype=object)

In [377]:
obj.isin(['b','c'])

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [379]:
obj[obj.isin(['b','c'])]

0    c
5    b
6    b
7    c
8    c
dtype: object

## 5.4总结